#!/usr/bin/env bash

# https://github.com/manjaro/packages-community/blob/master/i3/i3exit/blurlock
# originally this file is located in
# /usr/bin/

# convert 'src_img.jpg' -blur 0x50 -resize WidthxHeight 'dest_img.png'

img='/tmp/bgblur.png'

if [ -f "${img}" ]; then
	i3lock -i "${img}" -e -t
else
	i3lock -c 000000
fi
exit 0

